language: php

matrix:
  include:
    - php: 7.2
    - php: 7.3

before_script:
  - travis_retry composer self-update
  - travis_retry composer config http-basic.nova.laravel.com ${NOVA_USERNAME} ${NOVA_PASSWORD}
  - travis_retry composer config --global github-protocols https
  - travis_retry composer install --no-interaction --prefer-source

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml  --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
